language: node_js

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g grunt-cli karma
  - npm install coveralls

before_script:
  - jspm config registries.github.auth $GITHUBTOKEN
  - jspm install

# after_success:
#   - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
