language: node_js

node_js:
  - "0.12"

cache:
  directories:
    - node_modules

before_script:
  - npm install -g grunt karma
  - npm install coveralls
  - jspm config endpoints.github.auth $GITHUBTOKEN
  - jspm install

after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
